# Generated by Django 5.0.14 on 2026-03-09 14:04

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='note',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', '🍔 Food'), ('Transport', '🚗 Transport'), ('Rent', '🏠 Rent'), ('Shopping', '🛍️ Shopping'), ('Entertainment', '🎬 Entertainment'), ('Bills', '💡 Bills'), ('Healthcare', '🏥 Healthcare'), ('Education', '📚 Education'), ('Travel', '✈️ Travel'), ('Groceries', '🛒 Groceries'), ('Utilities', '⚡ Utilities'), ('Other', '📦 Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='expenses_ex_user_id_713a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='expenses_ex_user_id_207090_idx'),
        ),
    ]
